# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ae7168da9a521be52e1a45e49a9b9017c8a2f7351635902db2fb2f84adfc2587a7037c807c9e06aa71e1e0d9fd316e492174c88500f629c7f58e9275af55ba

test:
  secret_key_base: 52c8910f0f59c80447252febc926b7fd008c011221b8673591967122db67783d623550f516e8782323938407c495cfbcf3a8806a937340af98a7e0b349c088e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
